### ISSUE TITLE
AttributeError: 'dict' object has no attribute 'filterUpTags'

### ISSUE THREAD

**Issue by ErAzOr2k** [Wintermute0110/NARS#3]
Hi,

is this nice tool still in development?
I'm getting this error:

```
/NARS # python nars-console.py check n64
NARS Advanced ROM Sorting - Console No-Intro ROMs version 0.2.0_alpha1
[Parsing config file]
Reading configuration XML file 'nars-console-config.xml' ... done
[Check-filter ROM]
Filter name 'n64'
Using No-Intro parent/clone DAT
Parsing No-Intro XML DAT '/dats/Nintendo - Nintendo 64 (BigEndian) (Parent-Clone) (20190204-204558).dat' ... done
Total number of games  1025
Number of parents       418
Number of clones        607
[Scoring and filtering ROMs]
Traceback (most recent call last):
  File "nars-console.py", line 1764, in <module>
    elif command == 'check':          do_check(args.filterName)
  File "nars-console.py", line 1417, in do_check
    romMainList_list = filter_ROMs(filter_config)
  File "nars-console.py", line 1208, in filter_ROMs
    romMainList_list = get_Scores_and_Filter(romMainList_list, rom_Tag_dic, filter_config)
  File "nars-console.py", line 1059, in get_Scores_and_Filter
    upTag_list      = filter_config.filterUpTags
AttributeError: 'dict' object has no attribute 'filterUpTags'
```

**Comment by Wintermute0110** [comment]
No. The functionality provided by NARS is being merged in the Kodi mediacenter addons plugin.program.AEL and plugin.program.AML.
